/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.indvd00m.ascii.render.Render;
import com.indvd00m.ascii.render.api.ICanvas;
import com.indvd00m.ascii.render.api.IContextBuilder;
import com.indvd00m.ascii.render.api.IRender;
import com.indvd00m.ascii.render.elements.PseudoText;

import java.io.File;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import java.io.FileOutputStream;

import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

public class App {
    public static void main(String[] args) throws Exception {
        // ASCII render output
        IRender render = new Render();
        IContextBuilder builder = render.newBuilder();
        builder.width(80).height(20);
        builder.element(new PseudoText("Schalda1"));
        ICanvas canvas = render.render(builder.build());
        String s = canvas.getText();
        System.out.println(s);

        // PDF creation
        try (PDDocument helloPdf = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.A4);
            helloPdf.addPage(page);

            try (PDPageContentStream contentStream = new PDPageContentStream(helloPdf, page)) {
                contentStream.beginText();
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 36);
                contentStream.newLineAtOffset(50, 700);
                contentStream.showText("Hello DevOps PDF");
                contentStream.endText();
            }

            helloPdf.save(new File("schalda1.pdf"));
        }

        // Create a simple Excel file (XLSX)
        try (XSSFWorkbook workbook = new XSSFWorkbook();
             FileOutputStream out = new FileOutputStream("schala1.xlsx")) {
            XSSFSheet sheet = workbook.createSheet("Sheet1");
            XSSFRow row = sheet.createRow(0);
            row.createCell(0).setCellValue("Hello");
            row.createCell(1).setCellValue("Excel");
            workbook.write(out);
        }

        // Create a simple Word file (DOCX)
        try (XWPFDocument doc = new XWPFDocument();
             FileOutputStream out = new FileOutputStream("schalda1.docx")) {
            XWPFParagraph para = doc.createParagraph();
            XWPFRun run = para.createRun();
            run.setText("Hello Word!");
            doc.write(out);
        }
    }
}
